Test cases for 7-base_geometry.py

Import module
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()

Case 1: test with value as int
>>> bg.integer_validator("my_int", 12)

Case 2: test with value as string
>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
...
TypeError: name must be an integer

Case 3: test with value as 0
>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

Case 4: test with value as negative int
>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
...
ValueError: distance must be greater than 0

Case 5: test with value as float
>>> bg.integer_validator("name", 2.6)
Traceback (most recent call last):
...
TypeError: name must be an integer

Case 6: test with value as list
>>> bg.integer_validator("name", [1, 2])
Traceback (most recent call last):
...
TypeError: name must be an integer

Case 7: test with value as tuple
>>> bg.integer_validator("name", (1, 2))
Traceback (most recent call last):
...
TypeError: name must be an integer

Case 8: test with value as boolean
>>> bg.integer_validator("name", True)
Traceback (most recent call last):
...
TypeError: name must be an integer

Case 9: test with value as NULL
>>> bg.integer_validator("name", None)
Traceback (most recent call last):
...
TypeError: name must be an integer

Case 10: test with no arguments
>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Case 11: test with only one argument
>>> bg.integer_validator("name")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

Case 12: test with more than 2 arguments
>>> bg.integer_validator("name", 1, 2)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

Case 13: test area
>>> print(bg.area())
Traceback (most recent call last):
...
Exception: area() is not implemented
